name: Python style

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  create:
    branches: [main]
    tags: ['**']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8]
    env:
      TZ: Europe/Berlin
      FORCE_COLOR: true
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: defaults, conda-forge
        channel-priority: true
        activate-environment: ecomp_experiment
        environment-file: environment.yml

    - name: check environment
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda env list

    - name: Update pip, wheel, and setuptools
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip wheel setuptools

    - name: finish setup
      shell: bash -l {0}
      run: |
        pre-commit install

    - name: Check formatting
      shell: bash -l {0}
      run: |
        pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
