name: Python style

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  create:
    branches: [main]
    tags: ['**']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8]
    env:
      TZ: Europe/Berlin
      FORCE_COLOR: true
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: install mamba
      shell: bash -l {0}
      run: |
        conda install mamba -c conda-forge --yes

    - name: create environment
      shell: bash -l {0}
      run: |
        mamba env create -f environment.yml
        conda info
        conda list
        conda env list

    - name: Update pip, wheel, and setuptools
      shell: bash -l {0}
      run: |
        conda activate ecomp_experiment
        python -m pip install --upgrade pip wheel setuptools

    - name: finish setup
      shell: bash -l {0}
      run: |
        conda activate ecomp_experiment
        pre-commit install

    - name: Check formatting
      shell: bash -l {0}
      run: |
        conda activate ecomp_experiment
        pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
